-- ────────────────────────────────────────────────────────────────────────
-- 2Odds Football Prediction — VIP auth & subscription schema
-- ────────────────────────────────────────────────────────────────────────
-- Run this once against your Supabase project (SQL Editor → New query).
--
-- Two concerns, two schemas:
--   next_auth (schema)  → NextAuth/Auth.js's own bookkeeping (users it has
--                          seen, sessions, magic-link verification tokens).
--                          Table shape here is fixed by @auth/supabase-adapter
--                          — do not rename columns.
--   public              → this app's own VIP membership record, written only
--                          by the Flutterwave webhook (service-role key).
--
-- All access happens server-side with the Supabase *service role* key, which
-- bypasses Row Level Security — so RLS below is enabled with no policies
-- (default-deny) purely as defense in depth against an anon-key leak.

-- ── next_auth: Auth.js bookkeeping ─────────────────────────────────────
create schema if not exists next_auth;

grant usage on schema next_auth to service_role;
grant all on all tables in schema next_auth to service_role;
alter default privileges in schema next_auth grant all on tables to service_role;

create table if not exists next_auth.users (
  id uuid not null default gen_random_uuid(),
  name text,
  email text,
  "emailVerified" timestamptz,
  image text,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
);

create table if not exists next_auth.sessions (
  id uuid not null default gen_random_uuid(),
  expires timestamptz not null,
  "sessionToken" text not null,
  "userId" uuid,
  constraint sessions_pkey primary key (id),
  constraint sessions_sessionToken_key unique ("sessionToken"),
  constraint sessions_userId_fkey foreign key ("userId")
    references next_auth.users (id) on delete cascade
);

create table if not exists next_auth.accounts (
  id uuid not null default gen_random_uuid(),
  type text not null,
  provider text not null,
  "providerAccountId" text not null,
  refresh_token text,
  access_token text,
  expires_at bigint,
  token_type text,
  scope text,
  id_token text,
  session_state text,
  oauth_token_secret text,
  oauth_token text,
  "userId" uuid,
  constraint accounts_pkey primary key (id),
  constraint provider_unique unique (provider, "providerAccountId"),
  constraint accounts_userId_fkey foreign key ("userId")
    references next_auth.users (id) on delete cascade
);

create table if not exists next_auth.verification_tokens (
  id bigint generated by default as identity,
  identifier text,
  token text,
  expires timestamptz not null,
  constraint verification_tokens_pkey primary key (id),
  constraint token_unique unique (token),
  constraint token_identifier_unique unique (token, identifier)
);

-- Lets the adapter's `supabase.auth.uid()` helper (unused here, but part of
-- the official adapter migration) resolve the current session's user id.
create or replace function next_auth.uid() returns uuid
language sql stable
as $$
  select nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::uuid;
$$;

alter table next_auth.users enable row level security;
alter table next_auth.sessions enable row level security;
alter table next_auth.accounts enable row level security;
alter table next_auth.verification_tokens enable row level security;

-- ── public: this app's VIP membership record ───────────────────────────
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users (id) on delete cascade,
  email text not null unique,
  is_vip boolean not null default false,
  vip_expires_at timestamptz,
  flutterwave_tx_ref text,
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_email_idx on public.subscriptions (email);

alter table public.users enable row level security;
alter table public.subscriptions enable row level security;
-- No policies: only the service-role key (server-only, never shipped to the
-- browser) may read/write these tables. Anon/authenticated roles get nothing.
